/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewGUI;

/**
 *
 * @author CARLOS-ADMIN
 */
public class VistaRequerimientosReto5 extends javax.swing.JFrame {

    /**
     * Creates new form VistaRequerimientosReto5
     */
    public VistaRequerimientosReto5() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Requerimientos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrequerimiento1 = new javax.swing.JButton();
        btnrequerimiento2 = new javax.swing.JButton();
        btnrequerimiento3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrequerimiento1.setText("Requerimiento 1");
        btnrequerimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequerimiento1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnrequerimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 38));

        btnrequerimiento2.setText("Requerimiento 2");
        btnrequerimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequerimiento2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnrequerimiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 38));

        btnrequerimiento3.setText("Requerimiento 3");
        btnrequerimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequerimiento3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnrequerimiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrequerimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequerimiento1ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento1Reto5 vr = new VistaRequerimiento1Reto5();
        vr.setVisible(true);
        
    }//GEN-LAST:event_btnrequerimiento1ActionPerformed

    private void btnrequerimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequerimiento2ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento2Reto5 vr = new VistaRequerimiento2Reto5();
        vr.setVisible(true);
    }//GEN-LAST:event_btnrequerimiento2ActionPerformed

    private void btnrequerimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequerimiento3ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento3Reto5 vr = new VistaRequerimiento3Reto5();
        vr.setVisible(true);
    }//GEN-LAST:event_btnrequerimiento3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosReto5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientosReto5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrequerimiento1;
    private javax.swing.JButton btnrequerimiento2;
    private javax.swing.JButton btnrequerimiento3;
    // End of variables declaration//GEN-END:variables
}
